import { motion } from 'framer-motion';
import { FaCheckCircle, FaFileImport, FaSpinner, FaArrowRight } from 'react-icons/fa';

interface Step4ImportProps {
  markdown: string;
  isImporting: boolean;
  handleFileImport: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleImport: () => void;
  setMarkdown: (v: string) => void;
}

export function Step4Import({
  markdown,
  isImporting,
  handleFileImport,
  handleImport,
  setMarkdown,
}: Step4ImportProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.3 }}
      className="bg-white rounded-2xl p-6 border border-[rgba(0,0,0,0.1)] shadow-sm"
    >
      <div className="flex items-center gap-4 mb-6">
        <div className="w-10 h-10 rounded-xl bg-[rgba(0,117,222,0.08)] border border-[rgba(0,117,222,0.1)] text-[#0075de] flex items-center justify-center text-lg font-bold">
          4
        </div>
        <div>
          <h3 className="font-bold text-[rgba(0,0,0,0.95)]">Import Result File</h3>
          <p className="text-warm-400 text-xs">
            Upload the .md file generated by AI to finalize your resume.
          </p>
        </div>
      </div>

      <div className="space-y-4">
        <div
          onClick={() => document.getElementById('md-upload')?.click()}
          className={`relative group w-full h-32 border-2 border-dashed rounded-2xl transition-all cursor-pointer flex flex-col items-center justify-center gap-3 \${
            markdown
              ? 'border-[#2a9d99] bg-[#2a9d99]/[0.02]'
              : 'border-[rgba(0,0,0,0.1)] hover:border-[#0075de] hover:bg-[#0075de]/[0.02]'
          }`}
        >
          <input
            id="md-upload"
            type="file"
            accept=".md,.txt"
            className="hidden"
            onChange={handleFileImport}
          />

          {isImporting ? (
            <FaSpinner className="text-2xl text-[#0075de] animate-spin" />
          ) : markdown ? (
            <>
              <div className="w-12 h-12 rounded-full bg-[#2a9d99]/10 text-[#2a9d99] flex items-center justify-center text-xl">
                <FaCheckCircle />
              </div>
              <p className="text-[11px] font-bold text-[#2a9d99]">File Loaded & Ready</p>
            </>
          ) : (
            <>
              <div className="w-12 h-12 rounded-full bg-[rgba(0,0,0,0.03)] text-warm-400 flex items-center justify-center text-xl group-hover:scale-110 transition-transform">
                <FaFileImport />
              </div>
              <p className="text-[11px] font-bold text-warm-500">Click to upload .md file</p>
            </>
          )}
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-[11px] text-warm-400 leading-relaxed max-w-sm">
            Once uploaded, we'll automatically parse your resume and open the editor.
          </p>
          {markdown && !isImporting && (
            <button
              onClick={handleImport}
              className="w-full sm:w-auto px-8 py-3 bg-[#0075de] text-white rounded-xl font-bold shadow-lg shadow-[rgba(0,117,222,0.2)] hover:bg-[#005bab] hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2 group"
            >
              Finish & Edit
              <FaArrowRight className="text-xs group-hover:translate-x-1 transition-transform" />
            </button>
          )}
        </div>

        <details className="mt-4">
          <summary className="text-[10px] text-warm-300 cursor-pointer hover:text-warm-500 transition-colors list-none text-center">
            Wait, I'd rather paste the text manually
          </summary>
          <div className="mt-4">
            <textarea
              value={markdown}
              onChange={e => setMarkdown(e.target.value)}
              placeholder="Paste your markdown here..."
              className="w-full h-32 p-3 bg-[#fcfcfb] border border-[rgba(0,0,0,0.08)] rounded-xl text-[11px] font-mono focus:outline-none focus:ring-2 focus:ring-[#0075de] transition-all resize-none"
            />
          </div>
        </details>
      </div>
    </motion.div>
  );
}
