import { ResumeData, TemplateSettings, Project, Language } from '../types/resume'

export class LatexService {
  /**
   * Escape special LaTeX characters
   */
  private escapeLatex(text: string | undefined | null): string {
    if (!text) return ''
    return text
      .replace(/\\/g, '\\textbackslash ')
      .replace(/([&%$#_{}])/g, '\\$1')
      .replace(/~/g, '\\textasciitilde ')
      .replace(/\^/g, '\\textasciicircum ')
  }

  /**
   * Generate LaTeX source code from resume data
   */
  generateResumeLatex(data: ResumeData, settings: TemplateSettings): string {
    const {
      personal,
      education,
      experience,
      skills,
      projects = [],
      languages = [],
      summary,
      honors = [],
      certificates = [],
      publications = []
    } = data

    // Escape all user data
    const escapedPersonal = {
      ...personal,
      firstName: this.escapeLatex(personal.firstName),
      lastName: this.escapeLatex(personal.lastName),
      position: this.escapeLatex(personal.position),
      address: this.escapeLatex(personal.address),
      mobile: this.escapeLatex(personal.mobile),
      email: this.escapeLatex(personal.email),
      homePage: this.escapeLatex(personal.homePage),
      linkedin: this.escapeLatex(personal.linkedin),
      gitlab: this.escapeLatex(personal.gitlab),
      twitter: this.escapeLatex(personal.twitter),
      quote: this.escapeLatex(personal.quote)
    }

    const escapedSummary = this.escapeLatex(summary)

    const escapedExperience = experience.map(exp => ({
      ...exp,
      company: this.escapeLatex(exp.company),
      position: this.escapeLatex(exp.position),
      location: this.escapeLatex(exp.location),
      description: this.escapeLatex(exp.description),
      highlights: exp.highlights ? exp.highlights.map(h => this.escapeLatex(h)) : []
    }))

    const escapedEducation = education.map(edu => ({
      ...edu,
      school: this.escapeLatex(edu.school),
      degree: this.escapeLatex(edu.degree),
      field: this.escapeLatex(edu.field),
      location: this.escapeLatex(edu.location),
      description: this.escapeLatex(edu.description)
    }))

    const escapedSkills = skills.map(skill => ({
      ...skill,
      category: this.escapeLatex(skill.category),
      name: this.escapeLatex(skill.name)
    }))

    const escapedProjects = projects.map(proj => ({
      ...proj,
      name: this.escapeLatex(proj.name),
      description: this.escapeLatex(proj.description),
      technologies: proj.technologies ? proj.technologies.map(t => this.escapeLatex(t)) : []
    }))

    // Build personal information commands
    const personalInfoCommands = this.buildPersonalInfoCommands(escapedPersonal as any)
    const colorCommand = settings.customColor
      ? `\\definecolor{awesome}{HTML}{${settings.customColor.replace('#', '')}}`
      : `\\colorlet{awesome}{${settings.colorScheme}}`

    // Build content sections
    const summarySection = escapedSummary ? this.buildSummarySection(escapedSummary) : ''
    const experienceSection = escapedExperience.length > 0 ? this.buildExperienceSection(escapedExperience as any) : ''
    const educationSection = escapedEducation.length > 0 ? this.buildEducationSection(escapedEducation as any) : ''
    const skillsSection = escapedSkills.length > 0 ? this.buildSkillsSection(escapedSkills as any) : ''
    const projectsSection = escapedProjects.length > 0 ? this.buildProjectsSection(escapedProjects as any) : ''
    const languagesSection = languages.length > 0 ? this.buildLanguagesSection(languages) : ''
    const honorsSection = honors.length > 0 ? this.buildHonorsSection(honors.map(h => this.escapeLatex(h))) : ''
    const certificatesSection = certificates.length > 0 ? this.buildCertificatesSection(certificates.map(c => this.escapeLatex(c))) : ''
    const publicationsSection = publications.length > 0 ? this.buildPublicationsSection(publications.map(p => this.escapeLatex(p))) : ''

    const latex = `%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode
% Awesome CV LaTeX Template for CV/Resume
%
% Generated by Web Resume Generator
% https://github.com/yourusername/web-resume

%-------------------------------------------------------------------------------
% CONFIGURATIONS
%-------------------------------------------------------------------------------
\\documentclass[${settings.fontSize}, ${settings.paperSize}]{${settings.className || 'classic-professional'}}

% Configure page margins with geometry
\\geometry{left=1.4cm, top=.8cm, right=1.4cm, bottom=1.8cm, footskip=.5cm}

% Color for highlights
${colorCommand}

% Colors for text
% \\definecolor{darktext}{HTML}{414141}
% \\definecolor{text}{HTML}{333333}
% \\definecolor{graytext}{HTML}{5D5D5D}
% \\definecolor{lighttext}{HTML}{999999}
% \\definecolor{sectiondivider}{HTML}{5D5D5D}

% Set false if you don't want to highlight section with awesome color
\\setbool{acvSectionColorHighlight}{${settings.sectionColorHighlight}}

% If you would like to change the social information separator from a pipe (|) to something else
% \\renewcommand{\\acvHeaderSocialSep}{\\quad\\textbar\\quad}

%-------------------------------------------------------------------------------
% PERSONAL INFORMATION
%-------------------------------------------------------------------------------
${personalInfoCommands}

%-------------------------------------------------------------------------------
\\begin{document}

% Print the header with above personal information
% Give optional argument to change alignment(C: center, L: left, R: right)
\\makecvheader[${settings.headerAlignment}]

% Print the footer with 3 arguments(<left>, <center>, <right>)
% Leave any of these blank if they are not needed
\\makecvfooter
  {\\today}
  {${personal.firstName} ${personal.lastName}~~~·~~~Résumé}
  {\\thepage}

%-------------------------------------------------------------------------------
% CV/RESUME CONTENT
%-------------------------------------------------------------------------------
${summarySection}
${experienceSection}
${educationSection}
${skillsSection}
${projectsSection}
${languagesSection}
${honorsSection}
${certificatesSection}
${publicationsSection}

%-------------------------------------------------------------------------------
\\end{document}
`
    return latex
  }

  private buildPersonalInfoCommands(personal: ResumeData['personal']): string {
    const commands: string[] = []

    // Photo
    if (personal.photo) {
      const { shape = 'rectangle', edge = false, position = 'right' } = personal.photo
      const edgeOpt = edge ? 'edge' : 'noedge'
      commands.push(`\\photo[${shape},${edgeOpt},${position}]{${personal.photo.url}}`)
    }

    // Name and position
    commands.push(`\\name{${personal.firstName}}{${personal.lastName}}`)
    if (personal.position) {
      commands.push(`\\position{${personal.position}}`)
    }

    // Contact information
    if (personal.address) commands.push(`\\address{${personal.address}}`)
    if (personal.mobile) commands.push(`\\mobile{${personal.mobile}}`)
    if (personal.email) commands.push(`\\email{${personal.email}}`)
    if (personal.homePage) commands.push(`\\homepage{${personal.homePage}}`)
    if (personal.linkedin) commands.push(`\\linkedin{${personal.linkedin}}`)
    if (personal.gitlab) commands.push(`\\gitlab{${personal.gitlab}}`)
    if (personal.twitter) commands.push(`\\twitter{${personal.twitter}}`)

    // Quote
    if (personal.quote) {
      // Remove surrounding quotes if present
      let quoteText = personal.quote.trim()
      if (quoteText.startsWith('"') && quoteText.endsWith('"')) {
        quoteText = quoteText.slice(1, -1)
      }
      if (quoteText.startsWith("'") && quoteText.endsWith("'")) {
        quoteText = quoteText.slice(1, -1)
      }
      // Use LaTeX quotes: `` for opening, '' for closing
      commands.push(`\\quote{\`\`${quoteText}''}`)
    }

    return commands.join('\n')
  }

  private buildSummarySection(summary: string): string {
    return `%-------------------------------------------------------------------------------
% SUMMARY
%-------------------------------------------------------------------------------
\\cvsection{Summary}

\\begin{cvparagraph}

${summary}

\\end{cvparagraph}
`
  }

  private buildExperienceSection(experiences: ResumeData['experience']): string {
    let section = `%-------------------------------------------------------------------------------
% EXPERIENCE
%-------------------------------------------------------------------------------
\\cvsection{Experience}

\\begin{cventries}

`

    experiences.forEach(exp => {
      const endDate = exp.endDate ? exp.endDate : 'Present'
      const highlightsStr = (exp.highlights && exp.highlights.length > 0)
        ? `\\begin{cvitems}
${exp.highlights.map(item => `  \\item {${item}}`).join('\n')}
\\end{cvitems}`
        : (exp.description ? `\\begin{cvitems}
  \\item {${exp.description}}
\\end{cvitems}` : '')

      section += `  \\cventry
    {${exp.position}}
    {${exp.company}}
    {${exp.location || ''}}
    {${exp.startDate} -- ${endDate}}
    {${highlightsStr}}

`
    })

    section += `\\end{cventries}
`
    return section
  }

  private buildEducationSection(educations: ResumeData['education']): string {
    let section = `%-------------------------------------------------------------------------------
% EDUCATION
%-------------------------------------------------------------------------------
\\cvsection{Education}

\\begin{cventries}

`

    educations.forEach(edu => {
      const endDate = edu.endDate ? edu.endDate : 'Present'
      const degreeStr = edu.field ? `${edu.degree} in ${edu.field}` : edu.degree
      const gpaStr = edu.gpa ? ` (GPA: ${edu.gpa})` : ''
      const descriptionStr = edu.description ? `\\begin{cvitems}
  \\item {${edu.description}}
\\end{cvitems}` : ''

      section += `  \\cventry
    {${degreeStr}${gpaStr}}
    {${edu.school}}
    {${edu.location || ''}}
    {${edu.startDate} -- ${endDate}}
    {${descriptionStr}}

`
    })

    section += `\\end{cventries}
`
    return section
  }

  private buildSkillsSection(skills: ResumeData['skills']): string {
    // Group by category
    const byCategory: Record<string, ResumeData['skills']> = {}
    skills.forEach(skill => {
      if (!byCategory[skill.category]) {
        byCategory[skill.category] = []
      }
      byCategory[skill.category].push(skill)
    })

    let section = `%-------------------------------------------------------------------------------
% SKILLS
%-------------------------------------------------------------------------------
\\cvsection{Skills}

\\begin{cvskills}

`

    Object.entries(byCategory).forEach(([category, categorySkills]) => {
      section += `  \\cvskill
    {${category}}
    {${categorySkills.map(s => s.name).join(', ')}}

`
    })

    section += `\\end{cvskills}
`
    return section
  }

  private buildProjectsSection(projects: ResumeData['projects']): string {
    let section = `%-------------------------------------------------------------------------------
% PROJECTS
%-------------------------------------------------------------------------------
\\cvsection{Projects}

\\begin{cventries}

`
    const projectList = projects || []
    projectList.forEach((project: Project) => {
      const techStr = (project.technologies && project.technologies.length > 0)
        ? `\\begin{cvitems}
  \\item \\textbf{Technologies:} ${project.technologies.join(', ')}
\\end{cvitems}`
        : ''

      section += `  \\cventry
    {Project}
    {${project.name}}
    {}
    {}
    {${project.description}${techStr}}

`
    })

    section += `\\end{cventries}
`
    return section
  }

  private buildLanguagesSection(languages: ResumeData['languages']): string {
    let section = `%-------------------------------------------------------------------------------\n% LANGUAGES\n%-------------------------------------------------------------------------------\n\\cvsection{Languages}\n\n\\begin{cvskills}\n\n`
    const langList = languages || []
    langList.forEach((lang: Language) => {
      section += `  \\cvskill
    {${lang.name}}
    {${lang.level}}

`
    })

    section += `\\end{cvskills}
`
    return section
  }

  private buildHonorsSection(honors: string[]): string {
    let section = `%-------------------------------------------------------------------------------
% HONORS
%-------------------------------------------------------------------------------
\\cvsection{Honors \\& Awards}

\\begin{cvhonors}

`
    honors.forEach(honor => {
      section += `  \\cvhonor
    {${honor}}
    {}{}{}

`
    })

    section += `\\end{cvhonors}
`
    return section
  }

  private buildCertificatesSection(certificates: string[]): string {
    let section = `%-------------------------------------------------------------------------------
% CERTIFICATIONS
%-------------------------------------------------------------------------------
\\cvsection{Certifications}

\\begin{cvhonors}

`
    certificates.forEach(cert => {
      section += `  \\cvhonor
    {${cert}}
    {}{}{}

`
    })

    section += `\\end{cvhonors}
`
    return section
  }

  private buildPublicationsSection(publications: string[]): string {
    let section = `%-------------------------------------------------------------------------------
% PUBLICATIONS
%-------------------------------------------------------------------------------
\\cvsection{Publications}

\\begin{cventries}

`
    publications.forEach(pub => {
      section += `  \\cventry
    {${pub}}
    {}{}{}{}

`
    })

    section += `\\end{cventries}
`
    return section
  }
}