import { ResumeData, TemplateSettings, Project, Language } from '../types/resume'

export class LatexService {
  /**
   * Generate LaTeX source code from resume data
   */
  generateResumeLatex(data: ResumeData, settings: TemplateSettings): string {
    const {
      personal,
      education,
      experience,
      skills,
      projects = [],
      languages = [],
      summary,
      honors = [],
      certificates = [],
      publications = []
    } = data

    // Build personal information commands
    const personalInfoCommands = this.buildPersonalInfoCommands(personal)
    const colorCommand = settings.customColor
      ? `\\definecolor{awesome}{HTML}{${settings.customColor.replace('#', '')}}`
      : `\\colorlet{awesome}{${settings.colorScheme}}`

    // Build content sections
    const summarySection = summary ? this.buildSummarySection(summary) : ''
    const experienceSection = experience.length > 0 ? this.buildExperienceSection(experience) : ''
    const educationSection = education.length > 0 ? this.buildEducationSection(education) : ''
    const skillsSection = skills.length > 0 ? this.buildSkillsSection(skills) : ''
    const projectsSection = projects.length > 0 ? this.buildProjectsSection(projects) : ''
    const languagesSection = languages.length > 0 ? this.buildLanguagesSection(languages) : ''
    const honorsSection = honors.length > 0 ? this.buildHonorsSection(honors) : ''
    const certificatesSection = certificates.length > 0 ? this.buildCertificatesSection(certificates) : ''
    const publicationsSection = publications.length > 0 ? this.buildPublicationsSection(publications) : ''

    const latex = `%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode
% Awesome CV LaTeX Template for CV/Resume
%
% Generated by Web Resume Generator
% https://github.com/yourusername/web-resume

%-------------------------------------------------------------------------------
% CONFIGURATIONS
%-------------------------------------------------------------------------------
\\documentclass[${settings.fontSize}, ${settings.paperSize}]{awesome-cv}

% Configure page margins with geometry
\\geometry{left=1.4cm, top=.8cm, right=1.4cm, bottom=1.8cm, footskip=.5cm}

% Color for highlights
${colorCommand}

% Colors for text
% \\definecolor{darktext}{HTML}{414141}
% \\definecolor{text}{HTML}{333333}
% \\definecolor{graytext}{HTML}{5D5D5D}
% \\definecolor{lighttext}{HTML}{999999}
% \\definecolor{sectiondivider}{HTML}{5D5D5D}

% Set false if you don't want to highlight section with awesome color
\\setbool{acvSectionColorHighlight}{${settings.sectionColorHighlight}}

% If you would like to change the social information separator from a pipe (|) to something else
% \\renewcommand{\\acvHeaderSocialSep}{\\quad\\textbar\\quad}

%-------------------------------------------------------------------------------
% PERSONAL INFORMATION
%-------------------------------------------------------------------------------
${personalInfoCommands}

%-------------------------------------------------------------------------------
\\begin{document}

% Print the header with above personal information
% Give optional argument to change alignment(C: center, L: left, R: right)
\\makecvheader[${settings.headerAlignment}]

% Print the footer with 3 arguments(<left>, <center>, <right>)
% Leave any of these blank if they are not needed
\\makecvfooter
  {\\today}
  {${personal.firstName} ${personal.lastName}~~~·~~~Résumé}
  {\\thepage}

%-------------------------------------------------------------------------------
% CV/RESUME CONTENT
%-------------------------------------------------------------------------------
${summarySection}
${experienceSection}
${educationSection}
${skillsSection}
${projectsSection}
${languagesSection}
${honorsSection}
${certificatesSection}
${publicationsSection}

%-------------------------------------------------------------------------------
\\end{document}
`
    return latex
  }

  private buildPersonalInfoCommands(personal: ResumeData['personal']): string {
    const commands: string[] = []

    // Photo
    if (personal.photo) {
      const { shape = 'rectangle', edge = false, position = 'right' } = personal.photo
      const edgeOpt = edge ? 'edge' : 'noedge'
      commands.push(`\\photo[${shape},${edgeOpt},${position}]{${personal.photo.url}}`)
    }

    // Name and position
    commands.push(`\\name{${personal.firstName}}{${personal.lastName}}`)
    if (personal.position) {
      commands.push(`\\position{${personal.position}}`)
    }

    // Contact information
    if (personal.address) commands.push(`\\address{${personal.address}}`)
    if (personal.mobile) commands.push(`\\mobile{${personal.mobile}}`)
    if (personal.email) commands.push(`\\email{${personal.email}}`)
    if (personal.homePage) commands.push(`\\homepage{${personal.homePage}}`)
    if (personal.linkedin) commands.push(`\\linkedin{${personal.linkedin}}`)
    if (personal.gitlab) commands.push(`\\gitlab{${personal.gitlab}}`)
    if (personal.twitter) commands.push(`\\twitter{${personal.twitter}}`)

    // Quote
    if (personal.quote) {
      // Remove surrounding quotes if present
      let quoteText = personal.quote.trim()
      if (quoteText.startsWith('"') && quoteText.endsWith('"')) {
        quoteText = quoteText.slice(1, -1)
      }
      if (quoteText.startsWith("'") && quoteText.endsWith("'")) {
        quoteText = quoteText.slice(1, -1)
      }
      // Use LaTeX quotes: `` for opening, '' for closing
      commands.push(`\\quote{\`\`${quoteText}''}`)
    }

    return commands.join('\n')
  }

  private buildSummarySection(summary: string): string {
    return `%-------------------------------------------------------------------------------
% SUMMARY
%-------------------------------------------------------------------------------
\\cvsection{Summary}

\\begin{cvparagraph}

${summary}

\\end{cvparagraph}
`
  }

  private buildExperienceSection(experiences: ResumeData['experience']): string {
    let section = `%-------------------------------------------------------------------------------
% EXPERIENCE
%-------------------------------------------------------------------------------
\\cvsection{Experience}

`

    experiences.forEach(exp => {
      const endDate = exp.endDate ? exp.endDate : 'Present'
      section += `\\cvexperience
  {${exp.position}}
  {${exp.company}}
  {${exp.location || ''}}
  {${exp.startDate} -- ${endDate}}

`
      if (exp.description) {
        section += `\\begin{cvitems}
`
        if (exp.highlights && exp.highlights.length > 0) {
          exp.highlights.forEach(item => {
            section += `  \\item {${item}}
`
          })
        } else {
          section += `  \\item {${exp.description}}
`
        }
        section += `\\end{cvitems}
`
      }
    })

    return section
  }

  private buildEducationSection(educations: ResumeData['education']): string {
    let section = `%-------------------------------------------------------------------------------
% EDUCATION
%-------------------------------------------------------------------------------
\\cvsection{Education}

`

    educations.forEach(edu => {
      const endDate = edu.endDate ? edu.endDate : 'Present'
      section += `\\cveducation
  {${edu.degree}}
  {${edu.school}}
  {${edu.location || ''}}
  {${edu.startDate} -- ${endDate}}
  {${edu.field || ''}}
  {${edu.gpa || ''}}

`
      if (edu.description) {
        section += `\\begin{cvitems}
  \\item {${edu.description}}
\\end{cvitems}
`
      }
    })

    return section
  }

  private buildSkillsSection(skills: ResumeData['skills']): string {
    // Group by category
    const byCategory: Record<string, ResumeData['skills']> = {}
    skills.forEach(skill => {
      if (!byCategory[skill.category]) {
        byCategory[skill.category] = []
      }
      byCategory[skill.category].push(skill)
    })

    let section = `%-------------------------------------------------------------------------------
% SKILLS
%-------------------------------------------------------------------------------
\\cvsection{Skills}

`

    Object.entries(byCategory).forEach(([category, categorySkills]) => {
      section += `\\cvskill{${category}}{`
      section += categorySkills.map(s => s.name).join(', ')
      section += `}

`
    })

    return section
  }

  private buildProjectsSection(projects: ResumeData['projects']): string {
    let section = `%-------------------------------------------------------------------------------\n% PROJECTS\n%-------------------------------------------------------------------------------\n\\cvsection{Projects}\n\n`
    const projectList = projects || []
    projectList.forEach((project: Project) => {
      section += `\\cvproject
  {${project.name}}
  {${project.description}}

`
      if (project.technologies && project.technologies.length > 0) {
        section += `\\begin{cvitems}
  \\item \\textbf{Technologies:} ${project.technologies.join(', ')}
\\end{cvitems}
`
      }
    })

    return section
  }

  private buildLanguagesSection(languages: ResumeData['languages']): string {
    let section = `%-------------------------------------------------------------------------------\n% LANGUAGES\n%-------------------------------------------------------------------------------\n\\cvsection{Languages}\n\n\\begin{cvskills}\n\n`
    const langList = languages || []
    langList.forEach((lang: Language) => {
      section += `  \\cvskill
    {${lang.name}}
    {${lang.level}}

`
    })

    section += `\\end{cvskills}
`
    return section
  }

  private buildHonorsSection(honors: string[]): string {
    let section = `%-------------------------------------------------------------------------------
% HONORS
%-------------------------------------------------------------------------------
\\cvsection{Honors \\& Awards}

\\begin{cvhonors}

`
    honors.forEach(honor => {
      section += `  \\cvhonor
    {${honor}}
    {}{}{}

`
    })

    section += `\\end{cvhonors}
`
    return section
  }

  private buildCertificatesSection(certificates: string[]): string {
    let section = `%-------------------------------------------------------------------------------
% CERTIFICATIONS
%-------------------------------------------------------------------------------
\\cvsection{Certifications}

\\begin{cvhonors}

`
    certificates.forEach(cert => {
      section += `  \\cvhonor
    {${cert}}
    {}{}{}

`
    })

    section += `\\end{cvhonors}
`
    return section
  }

  private buildPublicationsSection(publications: string[]): string {
    let section = `%-------------------------------------------------------------------------------
% PUBLICATIONS
%-------------------------------------------------------------------------------
\\cvsection{Publications}

\\begin{cventries}

`
    publications.forEach(pub => {
      section += `  \\cventry
    {${pub}}
    {}{}{}{}

`
    })

    section += `\\end{cventries}
`
    return section
  }
}