import { ResumeData, TemplateSettings } from '../types/resume'

/**
 * Generate LaTeX source code from resume data
 * Ported from backend/src/services/latex.service.ts
 */
export function generateResumeLatex(data: ResumeData, settings: TemplateSettings): string {
  const {
    personal,
    education,
    experience,
    skills,
    projects = [],
    languages = [],
    summary,
    honors = [],
    certificates = [],
    publications = []
  } = data

  // Build personal information commands
  const personalInfoCommands = buildPersonalInfoCommands(personal)
  const colorCommand = settings.customColor
    ? `\\definecolor{awesome}{HTML}{${settings.customColor.replace('#', '')}}`
    : `\\colorlet{awesome}{${settings.colorScheme}}`

  // Build content sections
  const summarySection = summary ? buildSummarySection(summary) : ''
  const experienceSection = experience.length > 0 ? buildExperienceSection(experience) : ''
  const educationSection = education.length > 0 ? buildEducationSection(education) : ''
  const skillsSection = skills.length > 0 ? buildSkillsSection(skills) : ''
  const projectsSection = projects.length > 0 ? buildProjectsSection(projects) : ''
  const languagesSection = languages.length > 0 ? buildLanguagesSection(languages) : ''
  const honorsSection = honors.length > 0 ? buildHonorsSection(honors) : ''
  const certificatesSection = certificates.length > 0 ? buildCertificatesSection(certificates) : ''
  const publicationsSection = publications.length > 0 ? buildPublicationsSection(publications) : ''

  return `%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode
% Awesome CV LaTeX Template for CV/Resume
%
% Generated by SmartResume Generator

%-------------------------------------------------------------------------------
% CONFIGURATIONS
%-------------------------------------------------------------------------------
\\documentclass[${settings.fontSize}, ${settings.paperSize}]{awesome-cv}

% Configure page margins with geometry
\\geometry{left=1.4cm, top=.8cm, right=1.4cm, bottom=1.8cm, footskip=.5cm}

% Color for highlights
${colorCommand}

% Set false if you don't want to highlight section with awesome color
\\setbool{acvSectionColorHighlight}{${settings.sectionColorHighlight}}

%-------------------------------------------------------------------------------
% PERSONAL INFORMATION
%-------------------------------------------------------------------------------
${personalInfoCommands}

%-------------------------------------------------------------------------------
\\begin{document}

% Print the header with above personal information
\\makecvheader[${settings.headerAlignment}]

% Print the footer
\\makecvfooter
  {\\today}
  {${personal.firstName} ${personal.lastName}~~~·~~~Résumé}
  {\\thepage}

%-------------------------------------------------------------------------------
% CV/RESUME CONTENT
%-------------------------------------------------------------------------------
${summarySection}
${experienceSection}
${educationSection}
${skillsSection}
${projectsSection}
${languagesSection}
${honorsSection}
${certificatesSection}
${publicationsSection}

%-------------------------------------------------------------------------------
\\end{document}
`
}

function escapeLatex(str: string): string {
  return str
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/{/g, '\\{')
    .replace(/}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}')
}

function buildPersonalInfoCommands(personal: ResumeData['personal']): string {
  const commands: string[] = []

  if (personal.photo) {
    const { shape = 'rectangle', edge = false, position = 'right' } = personal.photo
    const edgeOpt = edge ? 'edge' : 'noedge'
    commands.push(`\\photo[${shape},${edgeOpt},${position}]{${personal.photo.url}}`)
  }

  commands.push(`\\name{${escapeLatex(personal.firstName || '')}}{${escapeLatex(personal.lastName || '')}}`)
  if (personal.position) {
    commands.push(`\\position{${escapeLatex(personal.position)}}`)
  }

  if (personal.address) commands.push(`\\address{${escapeLatex(personal.address)}}`)
  if (personal.mobile) commands.push(`\\mobile{${escapeLatex(personal.mobile)}}`)
  if (personal.email) commands.push(`\\email{${escapeLatex(personal.email)}}`)
  if (personal.homePage) commands.push(`\\homepage{${escapeLatex(personal.homePage)}}`)
  if (personal.linkedin) commands.push(`\\linkedin{${escapeLatex(personal.linkedin)}}`)
  if (personal.gitlab) commands.push(`\\gitlab{${escapeLatex(personal.gitlab)}}`)
  if (personal.twitter) commands.push(`\\twitter{${escapeLatex(personal.twitter)}}`)

  if (personal.quote) {
    let quoteText = personal.quote.trim()
    if (quoteText.startsWith('"') && quoteText.endsWith('"')) {
      quoteText = quoteText.slice(1, -1)
    }
    commands.push('\\quote{\\`\\`' + escapeLatex(quoteText) + "\\''}")
  }

  return commands.join('\n')
}

function buildSummarySection(summary: string): string {
  return `%-------------------------------------------------------------------------------
% SUMMARY
%-------------------------------------------------------------------------------
\\cvsection{Summary}

\\begin{cvparagraph}

${escapeLatex(summary)}

\\end{cvparagraph}
`
}

function buildExperienceSection(experiences: ResumeData['experience']): string {
  let section = `%-------------------------------------------------------------------------------
% EXPERIENCE
%-------------------------------------------------------------------------------
\\cvsection{Experience}

`

  experiences.forEach(exp => {
    const endDate = exp.endDate ? exp.endDate : 'Present'
    section += `\\cventry
  {${escapeLatex(exp.position)}}
  {${escapeLatex(exp.company)}}
  {${escapeLatex(exp.location || '')}}
  {${escapeLatex(exp.startDate)} -- ${escapeLatex(endDate)}}
  {}
`

    const items: string[] = []
    if (exp.description) {
      items.push(escapeLatex(exp.description))
    }
    if (exp.highlights && exp.highlights.length > 0) {
      exp.highlights.forEach(h => items.push(escapeLatex(h)))
    }

    if (items.length > 0) {
      section += `  {\\begin{cvitems}
`
      items.forEach(item => {
        section += `    \\item {${item}}
`
      })
      section += `  \\end{cvitems}}
`
    } else {
      section += `  {}
`
    }
    section += `
`
  })

  return section
}

function buildEducationSection(educations: ResumeData['education']): string {
  let section = `%-------------------------------------------------------------------------------
% EDUCATION
%-------------------------------------------------------------------------------
\\cvsection{Education}

`

  educations.forEach(edu => {
    const endDate = edu.endDate ? edu.endDate : 'Present'
    section += `\\cventry
  {${escapeLatex(edu.degree)}}
  {${escapeLatex(edu.school)}}
  {${escapeLatex(edu.location || '')}}
  {${escapeLatex(edu.startDate)} -- ${escapeLatex(endDate)}}
  {${escapeLatex(edu.field || '')}}
  {${escapeLatex(edu.gpa ? `GPA: ${edu.gpa}` : '')}}
`
    if (edu.description) {
      section += `  {\\begin{cvitems}
    \\item {${escapeLatex(edu.description)}}
  \\end{cvitems}}
`
    } else {
      section += `  {}
`
    }
    section += `
`
  })

  return section
}

function buildSkillsSection(skills: ResumeData['skills']): string {
  const byCategory: Record<string, ResumeData['skills']> = {}
  skills.forEach(skill => {
    if (!byCategory[skill.category]) {
      byCategory[skill.category] = []
    }
    byCategory[skill.category].push(skill)
  })

  let section = `%-------------------------------------------------------------------------------
% SKILLS
%-------------------------------------------------------------------------------
\\cvsection{Skills}

\\begin{cvskills}
`

  Object.entries(byCategory).forEach(([category, categorySkills]) => {
    section += `  \\cvskill
    {${escapeLatex(category)}}
    {${categorySkills.map(s => escapeLatex(s.name)).join(', ')}}
`
  })

  section += `\\end{cvskills}
`

  return section
}

function buildProjectsSection(projectList: ResumeData['projects']): string {
  let section = `%-------------------------------------------------------------------------------
% PROJECTS
%-------------------------------------------------------------------------------
\\cvsection{Projects}

`

  const projects = projectList || []
  projects.forEach((project: NonNullable<typeof projectList>[number]) => {
    section += `\\cventry
  {${escapeLatex(project.name)}}
  {${escapeLatex(project.description)}}
  {}
  {}
  {}
`
    if (project.technologies && project.technologies.length > 0) {
      section += `  {\\begin{cvitems}
    \\item \\textbf{Technologies:} ${project.technologies.map((t: string) => escapeLatex(t)).join(', ')}
  \\end{cvitems}}
`
    } else {
      section += `  {}
`
    }
    section += `
`
  })

  return section
}

function buildLanguagesSection(languageList: ResumeData['languages']): string {
  let section = `%-------------------------------------------------------------------------------
% LANGUAGES
%-------------------------------------------------------------------------------
\\cvsection{Languages}

\\begin{cvskills}
`

  const languages = languageList || []
  languages.forEach((lang: NonNullable<typeof languageList>[number]) => {
    section += `  \\cvskill
    {${escapeLatex(lang.name)}}
    {${escapeLatex(lang.level)}}
`
  })

  section += `\\end{cvskills}
`

  return section
}

function buildHonorsSection(honors: string[]): string {
  let section = `%-------------------------------------------------------------------------------
% HONORS
%-------------------------------------------------------------------------------
\\cvsection{Honors \\& Awards}

\\begin{cvhonors}
`

  honors.forEach(honor => {
    section += `  \\cvhonor
    {${escapeLatex(honor)}}
    {}{}{}
`
  })

  section += `\\end{cvhonors}
`

  return section
}

function buildCertificatesSection(certificates: string[]): string {
  let section = `%-------------------------------------------------------------------------------
% CERTIFICATIONS
%-------------------------------------------------------------------------------
\\cvsection{Certifications}

\\begin{cvhonors}
`

  certificates.forEach(cert => {
    section += `  \\cvhonor
    {${escapeLatex(cert)}}
    {}{}{}
`
  })

  section += `\\end{cvhonors}
`

  return section
}

function buildPublicationsSection(publications: string[]): string {
  let section = `%-------------------------------------------------------------------------------
% PUBLICATIONS
%-------------------------------------------------------------------------------
\\cvsection{Publications}

\\begin{cventries}
`

  publications.forEach(pub => {
    section += `  \\cventry
    {${escapeLatex(pub)}}
    {}{}{}{}
`
  })

  section += `\\end{cventries}
`

  return section
}
